<!DOCTYPE html>
<HTML>
<link rel="stylesheet" type="text/css" href="teacherHomePage.css">
<script src="tabcontent.js" type="text/javascript"></script>
<script src="jquery-1.11.2.js"></script>
<?php include_once 'php_control.php'; ?>

<HEAD>
    <style>
        div#load_screen{
            background:#FFF;
            opacity:0.7;
            position:fixed;
            z-index:10;
            top: 0px;
            width:100%;
            height:100%;
        }
    </style>
    <script>
        window.addEventListener("load", function(){

            var load_screen = document.getElementById("load_screen");
            document.body.removeChild(load_screen);
        });
    </script>
    <TITLE>
        MegaTest - Online Testing Application
    </TITLE>

</HEAD>

<BODY style="background:#F6F9FC; font-family:Arial;">
<div id="load_screen"><img src="images/megamonkeysloading.png" />loading document</div>
<div class="header">
    <img src="images/header.png" class="header"/>
    <img src="images/logo.png" class="testLogo"/>
    <form action="logout.php"><input type="submit" value="Sign out" class="logout-button"></form>
</div>

<div id='cssmenu'>
    <ul>
        <li class='loginPage.html'><a href='#'><span>Home</span></a></li>
        <li><a href='#'><span>About</span></a></li>
        <li><a href='#'><span>Team</span></a></li>
        <li class='last'><a href='#'><span>Contact</span></a></li>
    </ul>
</div>



<div class="content">
   <form action="testMakingPage.php"><input type="submit" value="+ Create Test" class="create-button"></form>

   <div class="courses">
      <table id="courseTable">
         <?php $class_list = get_class_list(); ?>
      </table>
   </div>

   <span id='classTitle'></span><br />

   <div class="testEachCourse">
      <div class="loader"></div>
      <table id="testTable">
         <!-- Table Elements Generated By AJAX Script -->
      </table>
   </div>
</div>


<div class="footer"></br>
   <img src="images/footerblue.png" class="footerblue"/>
   <ft>&copy; MegaMonkeys, Inc. - Pensacola Christian College 2015</ft>
</div>
</BODY>
</HTML>


<script type="text/javascript">
   $(document).ready(function() {

      $.ajaxSetup({ cache: false });
   });

   var $class_list = <?php echo json_encode($class_list) ?>;
      //[0]-COURSE_NO [1]-SECTION_NO [2]-SECTION_ID [3]-COURSE_DESCRIPTION
   get_class_test(Object.keys($class_list)[0]);

   function get_class_test(section_no) {
      //$("#testTable").attr("display", "none");
      $("#testTable").fadeOut(1);
      $(".loader").fadeIn("slow");
      document.getElementById("classTitle").innerHTML = $class_list[section_no];
      var data = 'php_control.php?section_no=' + section_no;
      $('#testTable').load(data);

   }
   $(document).ajaxComplete(function() {
      $(".loader").fadeOut(1);
      $("#testTable").fadeIn("slow");
   });

</script>