<!DOCTYPE html>
<HTML>
<link rel="stylesheet" type="text/css" href="testGradingPage.css">
<script src="tabcontent.js" type="text/javascript"></script>
<script src="./jquery-1.11.2.js"></script>
<?php include_once 'testGradingPage_control.php'; ?>
<HEAD>
    <style>
        div#load_screen{
            background:#FFF;
            opacity:0.7;
            position:fixed;
            z-index:10;
            top: 0px;
            width:100%;
            height:100%;
        }
    </style>
    <script>
        window.addEventListener("load", function(){
            var load_screen = document.getElementById("load_screen");
            document.body.removeChild(load_screen);
        });
		$( window ).resize(function() {
			page_resize();
		});
		$(function() {
			page_resize();
		});
		function page_resize() {
			//alert( $(window).height() + " " + $(document).height());
			$("#studentInformation").css("max-height", $(window).height() - 300);
         $(".testQuestions").css("min-height", $(window).height() - 300);
		}
    </script>
    <TITLE>
        MegaTest - Online Testing Application
    </TITLE>

</HEAD>

<BODY style="background:#F6F9FC; font-family:Arial;">
   <div id="load_screen"><img src="images/megamonkeysloading.png" />loading document</div>


   <div class="header">
      <img src="images/header.png" class="header"/>
      <img src="images/logo.png" class="testLogo"/>
      <form action="logout.php"><input type="submit" value="Sign out" class="logout-button"></form>
   </div>

   <div id='cssmenu'>
      <ul>
         <li class='loginPage.html'><a href='./teacherHomePage.php'><span>Home</span></a></li>
         <li><a href='#'><span>About</span></a></li>
         <li><a href='#'><span>Team</span></a></li>
         <li class='last'><a href='#'><span>Contact</span></a></li>
      </ul>
   </div>

   <div id="wrapper">
      <div id="test_info">
         <table>
            <tr>
               <td>Test Name</td>
               <td>Student Name</td>
               <td>Student Point</td>
               <td>Total Point</td>
               <td>%</td>
               <td>Save</td>
            </tr>
            <tr>
               <td id="f_t_name"></td>
               <td id="f_s_name"></td>
               <td id="f_s_point"></td>
               <td id="f_t_point"></td>
               <td id="f_percent"></td>
               <td id="f_save"><button id="t_save" type="button" onclick="testing()">Save</button></td>
            </tr>
         </table>
      </div>

      <div class="content">
         <div id="studentList">Student List:</div>
         <div id="studentInformation">
            <table id="studentTable">
               <?php get_student_list(); ?>
            </table>
         </div>

         <span id='classTitle'></span><br />

         <div class="testQuestions">
            <div class="loader"></div>
            <table id="test_table" class="table_border_style">
                <!-- Table Elements Generated By AJAX Script -->
            </table>
         </div>
      </div>

      <div class="footer"></br>
         <img src="images/footerblue.png" class="footerblue"/>
         <div>&copy; MegaMonkeys, Inc. - Pensacola Christian College 2015</div>
      </div>
   </div>

</BODY>
</HTML>

<script type="text/javascript">
   $(document).ready(function() { $.ajaxSetup({ cache: false }); });
   $(".loader").fadeOut(1);
   var test_info = <?php echo json_encode(get_test_info($_POST['gradeButton'])) ?>;
   f_t_name.innerHTML = test_info[0];
   t_id = <?php echo $_POST['gradeButton']; ?>;
   s_id = "";
   
   get_student_test(<?php echo $_POST['gradeButton']; ?>,<?php echo ($f_id) ?>,<?php echo json_encode($f_name); ?>);
   

   function get_student_test(test_id, student_id, s_name) {
      //alert(test_id + " " + student_id);
	  f_s_name.innerHTML = s_name;
      s_id = student_id;
	  f_s_point.innerHTML = f_t_point.innerHTML = f_percent.innerHTML = "";
	  
      var data = 'testGradingPage_control.php?action=get&test_id='+test_id+'&student_id='+student_id;

      $("#test_table").fadeOut(1);
      $(".loader").fadeIn("slow");
      $('#test_table').load(data, function (responseText, textStatus, XMLHttpRequest) {
         if (textStatus == "success") {
            calculate_total();
            document.getElementById("t_save").disabled = true;
            $(".loader").fadeOut(1);
            $("#test_table").fadeIn("slow");
         }
         if (textStatus == "error") {
            // oh noes!
			
         }
      });
   }

   $(document).ajaxComplete(function() {

   });

   function calculate_total() {
      var s_total = 0;
      var t_total = 0;
      for (i = 1; i <= document.getElementById("test_table").rows.length; i++) {
         //var current = parseInt(document.getElementById("p"+i).value);
         var current = document.getElementById("p"+i);
         if( ! $.isNumeric(current.value) )
            current.value = 0;
         s_total += parseInt(document.getElementById("p"+i).value);
         t_total += parseInt((document.getElementById("pointBox"+i).innerText).replace( /^\D+/g, ''));
         //t_total += parseInt((document.getElementById("pointBox1").innerText).substring(1));
      }
      f_s_point.innerHTML = s_total;
      f_t_point.innerHTML = t_total;
      var percent = parseFloat(s_total/t_total*100).toFixed(2);
      f_percent.innerHTML = ((!$.isNumeric(percent))?parseFloat(0).toFixed(2):percent);
      document.getElementById("t_save").disabled = false;
   }

   function testing() {
      var q_num = document.getElementById("test_table").rows.length;
      if( q_num != 0) {
         //TEST NO CAUTION !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         // NEED TO SET STUDENT ID
         var data = 'testGradingPage_control.php?s_id='+s_id+'&action=save&t_id='+t_id+'&count='+q_num;
         for (i = 1; i <= q_num; i++) {
            data += "&n"+i+"=" + document.getElementById("p"+i).value;
         }
         //#f_save
		 $("#test_table").fadeOut(1);
		 $(".loader").fadeIn("slow");
         $(this).load(data, function (responseText, textStatus, XMLHttpRequest) {
            if (textStatus == "success") {
               alert("saved");
               document.getElementById("t_save").disabled = true;
			   $(".loader").fadeOut(1);
               $("#test_table").fadeIn("slow");
            }
            if (textStatus == "error") {
               // oh noes!
			   alert(responseText);
            }
         });
      }
      else {

      }
   }

</script>