<!DOCTYPE html>
<HTML>
<link rel="stylesheet" type="text/css" href="testTakingPage.css">
<script src="tabcontent.js" type="text/javascript"></script>
<script src="jquery-1.11.2.js"></script>
<HEAD>
    <style>
        div#load_screen{
            background:#FFF;
            opacity:0.7;
            position:fixed;
            z-index:10;
            top: 0px;
            width:100%;
            height:100%;
        }
    </style>
    <script>
        window.addEventListener("load", function(){

            var load_screen = document.getElementById("load_screen");
            document.body.removeChild(load_screen);
        });
    </script>
    <TITLE>
        MegaTest - Online Testing Application
    </TITLE>

</HEAD>

<BODY style="background:#F6F9FC; font-family:Arial;">
<div id="load_screen"><img src="images/megamonkeysloading.png" />loading document</div>
<div class="header">
    <img src="images/header.png" class="header"/>
    <img src="images/logo.png" class="testLogo"/>
    <form action="logout.php"><input type="submit" value="Sign out" class="logout-button"></form>
</div>

<div id='cssmenu'>
    <ul>
        <li class='loginPage.html'><a href='#'><span>Home</span></a></li>
        <li><a href='#'><span>About</span></a></li>
        <li><a href='#'><span>Team</span></a></li>
        <li class='last'><a href='#'><span>Contact</span></a></li>
    </ul>
</div>



<div class="content">
   <form action="testMakingPage.php"><input type="submit" value="Submit" class="submit-button"></form>
   <div id="testInformation">
   <table>
   <tr>
   <td>Name: </td>
   <td>Bernike</td>
   </tr>
   <tr>
   <td>Class:</td>
   <td>CS414</td>
   </tr>
   <tr>
   <td>Test:</td>
   <td>Test # 1</td>
   </tr>
   <tr>
   <td>Time limit:</td>
   <td>2 : 00 : 00</td>
   </tr>
   </table>
   </div>

   <span id='classTitle'></span><br />

   <div class="testQuestions">
   <table>
	<tr><td id="trueFalse">
		<table>
		<tr>
			<td width="50px">
				1.
			</td>
			<td colspan="2" width="850">
				<span id="theQuestion">Dr. Geary teaches .NET programming class</span> (5)
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="radio" name="trueFalseAns" value="true">True
			</td>
			<td>
				<input type="radio" name="trueFalseAns" value="false">False
			</td>
		</tr>
		</table>
	</td></tr>
		
	<tr><td id="multipleChoice">
		<table>
		<tr>
			<td width="50px">
				2.
			</td>
			<td colspan="2" width="850">
				<span id="theQuestion">What is the first letter of an alphabet</span>(5)
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="radio" name="multipleChoiceAns" value="a">a
			</td>
			<td>
				<input type="radio" name="multipleChoiceAns" value="b">b
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="radio" name="multipleChoiceAns" value="c">c
			</td>
			<td>
				<input type="radio" name="multipleChoiceAns" value="d">d
			</td>
		</tr>
		</table>
	</td></tr>
	  
	<tr><td id="manyChoice">
		<table>
		<tr>
			<td width="50px">
				3.
			</td>
			<td colspan="2" width="850">
				<span id="theQuestion">Choose all that apply</span>(5)
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="checkbox" name="manyChoiceAns" value="house"> I have a house
			</td>
			<td>
				<input type="checkbox" name="manyChoiceAns" value="phone"> I have a phone
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="checkbox" name="manyChoiceAns" value="Bike"> I have a bike
			</td>
			<td>
				<input type="checkbox" name="manyChoiceAns" value="Car"> I have a car
			</td>
		</tr>
		</table>
	</td></tr>
		
	<tr><td id="shortAnswer">
		<table>
		<tr>
			<td width="50px">
				4.
			</td>
			<td width="850">
				<span id="theQuestion">Who invented facebook?</span>(5)
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="text" name="shortAns" value="">
			</td>
		</tr>
		</table>
		
	<tr><td id="essay">
		<table>
		<tr>
			<td width="50px">
				5.
			</td>
			<td width="850">
				<span id="theQuestion">What is DBMS(explain)?</span>(5)
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="text" name="essayAns" value="" class="essayText">
			</td>
		</tr>
		</table>
	</td></tr>
         <!-- Table Elements Generated By AJAX Script -->
   </table>
   </div>
</div>


<div class="footer"></br>
   <img src="images/footerblue.png" class="footerblue"/>
   <ft>&copy; MegaMonkeys, Inc. - Pensacola Christian College 2015</ft>
</div>
</BODY>
</HTML>